site_name: BAV API Python SDK
site_url: https://wppbav.github.io/bavapi-sdk-python

repo_name: wppbav/bavapi-sdk-python
repo_url: https://github.com/wppbav/bavapi-sdk-python

copyright: Copyright &copy; 2023 WPPBAV

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/wpp-bav-logo.svg
  favicon: assets/favicon.svg
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.annotate
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

extra_css: [extra.css]

extra:
  version:
    provider: mike

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

nav:
  - Home:
      - Introduction: index.md
      - Release Notes: release-notes.md
      - Roadmap: roadmap.md
  - Getting Started:
      - Authentication: getting-started/authentication.md
      - Installation: getting-started/installation.md
      - Install Reference classes: getting-started/reference-classes.md
  - Usage:
      - Basic Usage: usage/basic.md
      - Advanced Usage: usage/advanced.md
      - Usage Tips for Projects: usage/project-tips.md
  - Endpoints: endpoints/
  - Code Reference: reference/
  - Contributing: contributing.md
  - Fount API Reference: https://developer.wppbav.com/docs/2.x/intro

plugins:
  - search
  # - social
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
        - docs/fetch_contributing.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mike
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python-requests.org/en/master/objects.inv
          paths: [bavapi]
          options:
            docstring_style: numpy

watch:
  - bavapi
