name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup nox
        uses: wntrblm/nox@2023.04.22
        with:
          python-versions: ${{ matrix.python }}

      - name: Run unit tests
        run: nox -s tests-${{ matrix.python }}

      - name: Upload coverage data
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: ".coverage.*"

  coverage:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup nox
        uses: wntrblm/nox@2023.04.22
        with:
          python-versions: "3.12"

      - name: Download coverage data
        uses: actions/download-artifact@v3
        with:
          name: coverage-data

      - name: Combine and report coverage
        run: nox -s coverage

      - name: Make badge
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.COV_GIST_TOKEN }}
          gistID: 325c52d8f996801f615921912c08195d
          filename: covbadge.json
          label: coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}
